# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test ayelet_initmanager

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install & Config Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
    - name: Setup Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies & Run tests
      run: |
        poetry install --no-root
        poetry run sh scripts/lint.sh
        poetry run sh scripts/coverage.sh